output:
  rootDir: "./results/"
  prefix: result-
smpl:
  modelRootDir: ./models
  type: smplx # possible options smplx and smpl
  gender: MALE # possible options MALE, FEMALE, NEUTRAL
  ext: npz
  useVposerInit: false
data:
  renameFiles: false
  rootDir: ./samples
  personId: 0
  sampleImageFormat: "%%%.png"
  sampleNameFormat: "%%%.json"
  sampleCoords: !!python/tuple [1080, 1080]
camera:
  lr: 0.001
  patience: 10
  optimizer: Adam
pose:
  # device: cuda
  lr: 0.001
  optimizer: Adam # currently supported Adam, LBFGS
  iterations: 500
  useCameraIntrinsics: false
  bodyMeanLoss:
    enabled: false
    weight: 0.1
  bodyPrior:
    enabled: false
    weight: 0.01
  anglePrior:
    enabled: true
    weight: 0.01
    # idxWeights:
    #   - 0.5
    #   - 0.5
    #   - 0.25
    #   - 0.25
    # idx:
    #   - 56 # right elbow
    #   - 53 # left elbow
    #   - 12 # right knee
    #   - 9 # left knee
    # directions:
    #   - 1
    #   - -1
    #   - -1
    #   - -1
  confWeights:
    enabled: false
  vposerPath: "./vposer_v1_0"
preview:
  enable: true,
  keypoins:
    enable: true,
    radius: 0.01
    color: 1.0, 0.0, 1.0, 1.0
  keypoint_torso:
    enable: true,
    radius: 0.01
    color: 1.0, 0.0, 1.0, 1.0
  joints:
    enable: true
    radius: 0.01
    color: 0.0, 0.7, 0.0, 1.0
