output:
  rootDir: "./tests/17-02-21"
  prefix: ""
smpl:
  modelRootDir: ./models
  type: smplx # possible options smplx and smpl
  gender: MALE # possible options MALE, FEMALE, NEUTRAL
  ext: npz
  useVposerInit: false
data:
  renameFiles: false
  rootDir: ./output
  personId: 0
  sampleImageFormat: "input_%%%%%%%%%%%%_rendered.png"
  sampleNameFormat: "input_%%%%%%%%%%%%_keypoints.json"
  sampleCoords: !!python/tuple [1080, 1080]
camera:
  lr: 0.001
  patience: 10
  optimizer: Adam
pose:
  device: cuda
  lr: 0.01
  optimizer: Adam # currently supported Adam, LBFGS
  iterations: 150
  useCameraIntrinsics: true
  bodyMeanLoss:
    enabled: false
    weight: 0.1
  bodyPrior:
    enabled: true
    weight: 0.01
  anglePrior:
    enabled: true
    weight: 0.01
  angleLimitLoss:
    enabled: true
    weight: 0.1
  angleSumLoss:
    enabled: true
    weight: 0.01
  intersectLoss:
    enabled: true
    weight: 2.0
    maxCollisions: 8
    sigma: 0.5
  changeLoss:
    enabled: true
    weight: 2.0
  confWeights:
    enabled: false
  vposerPath: "./vposer_v1_0"
  temporal:
    enabled: true
    iterations: 75
    lr: 0.02
preview:
  enable: true,
  keypoins:
    enable: true,
    radius: 0.01
    color: 1.0, 0.0, 1.0, 1.0
  keypoint_torso:
    enable: true,
    radius: 0.01
    color: 1.0, 0.0, 1.0, 1.0
  joints:
    enable: true
    radius: 0.01
    color: 0.0, 0.7, 0.0, 1.0
