output:
  rootDir: "./tests/final-03"
  prefix: ""
smpl:
  modelRootDir: ./models
  type: smplx # possible options smplx and smpl
  gender: MALE # possible options MALE, FEMALE, NEUTRAL
  ext: npz
  useVposerInit: false
data:
  renameFiles: false
  rootDir: ./samples/video01
  personId: 0
  sampleImageFormat: "input_%%%%%%%%%%%%_rendered.png"
  sampleNameFormat: "input_%%%%%%%%%%%%_keypoints.json"
  sampleCoords: !!python/tuple [1080, 1080]
camera:
  lr: 0.001
  patience: 10
  optimizer: Adam
orientation:
  lr: 0.03
  optimizer: LBFGS
  iterations: 5
  joint_names: ["hip-left", "hip-right", "shoulder-left", "shoulder-right"] # joints to be used for optimization
pose:
  device: cuda
  lr: 0.01
  optimizer: Adam # currently supported Adam, LBFGS
  iterations: 200
  useCameraIntrinsics: true
  useOpenPoseConf: false # use openpose confidence to weight L2 distance loss
  bodyMeanLoss:
    enabled: false
    weight: 0.1
  bodyPrior:
    enabled: false
    weight: 0.01
  anglePrior:
    enabled: false
    weight: 0.2
    # optional per joint configurations
    angleIdx: [56, 53, 12, 9, 37, 40]
    directions: [-1, 1, -1, -1, 1, -1]
    # weights per joint
    weights: [0.4, 0.4, 0.4, 0.4, 0.2, 0.2]
  angleLimitLoss:
    enabled: false
    weight: 0.01
  angleSumLoss:
    enabled: false
    weight: 0.001
  intersectLoss:
    enabled: false
    weight: 0.5
    maxCollisions: 8
    sigma: 0.5
  changeLoss:
    enabled: true
    weight: 0.2
  confWeights:
    enabled: false
  vposerPath: "./vposer_v1_0"
  temporal:
    enabled: true
    iterations: 30
    lr: 0.01
preview:
  enable: true,
  keypoins:
    enable: true,
    radius: 0.01
    color: 1.0, 0.0, 1.0, 1.0
  keypoint_torso:
    enable: true,
    radius: 0.01
    color: 1.0, 0.0, 1.0, 1.0
  joints:
    enable: true
    radius: 0.01
    color: 0.0, 0.7, 0.0, 1.0
